Plugins/braintree
getapper/restlessness pull request #131
Opened 2021-05-05 07:30 UTC by TheGrinch00

Ho creato delle funzioni per:
- Customer
  - Create
  - Find
  - Delete
- PaymentMethod
  - Create
  - getFirst
- Subscription
  - Create
  - isAlreadySubscribed
  - Get all
- Discounts
  - Get all
  - Find by name

2021-05-05 11:43 UTC, antoniogiordano requested changes

2021-05-05 11:43 UTC, antoniogiordano commented on packages/plugins/braintree/src/braintree/index.ts
> +        const environment = process.env.RLN_IS_BRAINTREE_SANDBOX ? braintreeSdk.Environment.Sandbox : braintreeSdk.Environment.Production;
```suggestion
        const environment = process.env.RLN_BRAINTREE_IS_SANDBOX ? braintreeSdk.Environment.Sandbox : braintreeSdk.Environment.Production;
```

2021-05-06 12:35 UTC, TheGrinch00 commented on packages/plugins/braintree/src/braintree/index.ts
> +require('dotenv').config();
Without this, my keys were undefined

2021-05-06 13:13 UTC, antoniogiordano commented on packages/plugins/braintree/src/braintree/index.ts
> +require('dotenv').config();
got it, but from the project env vars will be loaded with automatically, so we can remove from here now

2021-05-06 13:13 UTC, antoniogiordano commented on packages/plugins/braintree/src/braintree/index.ts
> +require('dotenv').config();
```suggestion
```

2021-05-06 13:14 UTC, antoniogiordano approved these changes
Awesome, let's try it! As soon as we connect it to a project, we'll realize if we need to add or modify anything!

2021-05-06 13:14 UTC, merged