Feature/backend micro services
getapper/restlessness pull request #96
Opened 2020-10-06 17:05 UTC by androsanta

Added the following endpoints:
get /services
get /services/{name} (return list of service names)
delete /services/{name}

Currently get /services return the full JsonServerless object, should we filter some information?

2020-10-06 17:44 UTC, antoniogiordano requested changes

2020-10-06 17:44 UTC, antoniogiordano commented on packages/restlessness-cli/rln-backend/src/endpoints/delete-services-by-name/index.ts
> +export default LambdaHandler.bind(this, handler, validations, 'deleteServicesByName');
I think we use a custom handler for rln backend

2020-10-06 17:44 UTC, antoniogiordano commented on packages/restlessness-cli/rln-backend/src/endpoints/get-services-by-name/index.ts
> +export default LambdaHandler.bind(this, handler, validations, 'getServicesByName');
same here

2020-10-06 17:44 UTC, antoniogiordano commented on packages/restlessness-cli/rln-backend/src/exporter.ts
> +import postEndpoints from 'root/endpoints/post-endpoints';
I think we should remove module alias from rln backend

2020-10-06 17:44 UTC, antoniogiordano commented on packages/restlessness-cli/rln-backend/src/models/Service/index.ts
> +      .filter(s => s !== JsonServices.OFFLINE_SERVICE_NAME);
we should hide offline and shared as well, devs can use only services created by themselves

2020-10-07 07:59 UTC, androsanta commented
Should we return the full JsonServerless object (for get /services/{name}) or only some information?

2020-10-07 08:03 UTC, antoniogiordano commented
All the object is fine

2020-10-07 08:06 UTC, androsanta commented
👍🏽 im doing the post /services

2020-10-08 15:54 UTC, merged